In [2]:
from statsmodels.stats.weightstats import ztest as ztest
#IQ level od 20 patient
data = [88, 92, 93, 94, 96, 97, 98, 99, 100, 101, 101, 104, 105, 106, 106, 107, 109, 110, 111, 113]

ztest(data,value=105)


(-2.2580026843811565, 0.023945492077753237)

In [3]:
## t-test

In [7]:
ages = [10,15,20,21, 22,24,26,27, 28, 29, 31,35,38,39, 40,45,47,48,49,51,53,56,57,59,60,61,62,64,66,67,68,69,71,76,77,81,87,91]

In [8]:
import numpy as np
ages_mean=np.mean(ages)
ages_mean

49.21052631578947

In [26]:
sample_size=9
age_sample=np.random.choice(ages,sample_size)

In [33]:
age_sample

array([67, 20, 91, 45, 45, 21, 67, 29, 56])

In [34]:
np.mean(age_sample)

49.0

In [10]:
from scipy.stats import ttest_1samp

In [35]:
ttest_1samp(age_sample,30)

Ttest_1sampResult(statistic=2.398538731771652, pvalue=0.04327529973994045)

In [36]:
ttest_1samp(age_sample,31)

Ttest_1sampResult(statistic=2.2722998511520913, pvalue=0.05270092193843414)

In [37]:
ttest_1samp(age_sample,28)

Ttest_1sampResult(statistic=2.6510164930107734, pvalue=0.029209699637822256)

In [38]:
ttest_1samp(age_sample,29)

Ttest_1sampResult(statistic=2.5247776123912127, pvalue=0.03554332159386397)

In [39]:
## Consider another example
## Ages of the college students(population)
# 1 class student mean of all the ages

In [44]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)

In [45]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [46]:
classA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [47]:
classA_ages.mean()

46.9

In [57]:
_,p_value=ttest_1samp(classA_ages,popmean=school_ages.mean())

In [58]:
school_ages.mean()

53.303333333333335

In [71]:
if p_value<0.05:
    print("Reject the H0 value  ")
else:
    print("Accpet the H0 value  ")

Reject the H0 value  


In [67]:
import seaborn as sns

In [68]:
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [69]:
df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [1]:
sns.pairplot(df)

NameError: name 'sns' is not defined